import { SchemaObject } from 'openapi3-ts';
import { createComponentRef } from '../../../../../../utils/ref';

const websiteKeyResponse: SchemaObject = {
  title: 'Token Configuration Creation',
  type: 'object',
  description: 'Token configuration created response',
  properties: {
    id: {
      title: 'Token Configuration Id',
      type: 'string',
      description: 'The configuration unique id',
      example: '11401560-bffb-4ef3-a08e-989a15ed3c32',
    },
    websiteKey: {
      type: 'string',
      description: 'Key generated by the platform that the client\'s frontend must use to identify itself',
      readOnly: true,
      example: 'XXXXXXXXXXXXXX',
    }
  }
}

export const ref = createComponentRef(__filename);
export default websiteKeyResponse;